image: hseeberger/scala-sbt:latest

before_script:
  - export TZ=Europe/Amsterdam

stages:
  - test
  - build

sbt-test:
  stage: test
  script:
    - sbt coverage test coverageReport coverageAggregate
  tags:
    - docker

sbt-assembly:
  stage: build
  script:
    - sbt assembly
  tags:
    - docker
