language: scala
before_install:
  - export TZ=Europe/Amsterdam
jdk:
  - oraclejdk8
scala:
  - 2.12.1
script:
  - sbt clean coverage test coverageReport
  - sbt coverageAggregate
after_success:
  - sbt coveralls
